services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go-api
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - ./logs:/api/logs  # Optional: for log persistence