name: Deploy Go Application

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ main, master ]

jobs:  
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
           cd /home/vagrant/goprojects/src/go_git_action
           git pull
           docker compose up -d --build